### ISSUE TITLE
Add support for the OXRS LCD 

### ISSUE THREAD

**Issue by JamesKennewell** [Bedrock-Media-Designs/OXRS-BMD-PDU-ESP32-FW#3]
Correctly show on the LCD current state of each output and a way to monitor the current Amp draw on each output.

**Comment by sumnerboy12** [comment]
Prototype mock up by Moin

![image](https://user-images.githubusercontent.com/5060842/153701396-cd33fd48-e327-40a1-a658-2721e9a23845.png)
